package com.example.retrofitdemo.Testing

enum class Error {
    USERNAME_OR_PASSWORD_IS_EMPTY,
    USERNAME_IS_ALREADY_TAKEN,
    CONFIRMED_PASSWORD_IS_NOT_THE_SAME_AS_THE_REAL_PASSWORD,
    PASSWORD_CONTAINS_LESS_THAN_2_DIGITS,
    SUCCESS
}
